wall_width.png: wall_width.asy
	asy -f png wall_width.asy

eq_triangle.png: eq_triangle.asy
	asy -f png eq_triangle.asy

circle_radius_calc.png: circle_radius_calc.asy
	asy -f png circle_radius_calc.asy
